server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-server

eureka:
  client:
    # o eureka nao registra a si mesmo
    register-with-eureka: false
    fetch-registry: false
