server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-server

eureka:
  client:
    # eureka does not register with itself
    register-with-eureka: false
    fetch-registry: false
